<a href="https://colab.research.google.com/github/Selvithevar/generative-ai-course/blob/main/RNN_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [41]:
from tensorflow.keras.preprocessing.text import one_hot

In [42]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [43]:
## Define the vocabulary size
voc_size=10000

In [44]:
one_hot_repr=[one_hot(words,voc_size) for words in sent]
one_hot_repr

[[5474, 5801, 5753, 8922],
 [5474, 5801, 5753, 4828],
 [5474, 7198, 5753, 1842],
 [2046, 1987, 2690, 5990, 5543],
 [2046, 1987, 2690, 5990, 1857],
 [7218, 5474, 2503, 5753, 7253],
 [1346, 9753, 4119, 5990]]

In [45]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import pad_sequences

sent_len = 8
embedded_docs = pad_sequences(one_hot_repr,padding="post",maxlen=sent_len)
embedded_docs

array([[5474, 5801, 5753, 8922,    0,    0,    0,    0],
       [5474, 5801, 5753, 4828,    0,    0,    0,    0],
       [5474, 7198, 5753, 1842,    0,    0,    0,    0],
       [2046, 1987, 2690, 5990, 5543,    0,    0,    0],
       [2046, 1987, 2690, 5990, 1857,    0,    0,    0],
       [7218, 5474, 2503, 5753, 7253,    0,    0,    0],
       [1346, 9753, 4119, 5990,    0,    0,    0,    0]], dtype=int32)

In [46]:
dim=10 #featrue representation
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_len))
model.compile('adam','mse')

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [47]:
model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_6 (Embedding)              │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [48]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step


array([[[-0.02232144,  0.00177628, -0.01126182,  0.01903306,
         -0.02807498,  0.00426356, -0.03754268,  0.01309718,
          0.04287818,  0.04488708],
        [ 0.00194477,  0.04209999, -0.00214918,  0.01002274,
         -0.01306751,  0.01986647,  0.00650709, -0.03533275,
         -0.01177717, -0.02963808],
        [ 0.02131287,  0.00279512,  0.02911386, -0.03402659,
          0.0322469 , -0.04042877, -0.04632003, -0.01640699,
         -0.03953861, -0.03131998],
        [ 0.02350254,  0.00404493,  0.00528487, -0.00054917,
          0.04094703, -0.00877624, -0.04663652,  0.02406609,
         -0.04610764,  0.03587285],
        [ 0.00354239,  0.0111798 ,  0.02981624, -0.04848268,
         -0.02070452,  0.01045371,  0.0302467 , -0.04861459,
         -0.02194547, -0.00290967],
        [ 0.00354239,  0.0111798 ,  0.02981624, -0.04848268,
         -0.02070452,  0.01045371,  0.0302467 , -0.04861459,
         -0.02194547, -0.00290967],
        [ 0.00354239,  0.0111798 ,  0.02981624, -0.0

In [49]:
#ende to end deeplearning projects using rnn
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import imdb
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.layers import Embedding,SimpleRNN,Dense


In [50]:
max_features = 10000 #vocabulary size
(x_train,y_train),(x_test,y_test) = imdb.load_data(num_words=max_features)

# Print the shape of the data
print(f'Training data shape: {x_train.shape}, Training labels shape: {y_train.shape}')
print(f'Testing data shape: {x_test.shape}, Testing labels shape: {y_test.shape}')

Training data shape: (25000,), Training labels shape: (25000,)
Testing data shape: (25000,), Testing labels shape: (25000,)


In [51]:
sample_review = x_train[0]
sample_label = y_train[0]

print(f"sample review (as int):{sample_review}")
print(f"sample label: {sample_label}")


sample review (as int):[1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 2, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 2, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 2, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 2, 8, 4, 107, 117, 5952, 15, 256, 4, 2, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 2, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]
sample label: 1


In [52]:
#mapping of word index

word_index = imdb.get_word_index()
reverse_wrd_index = {value:key for key,value in word_index.items()}
reverse_wrd_index

{34701: 'fawn',
 52006: 'tsukino',
 52007: 'nunnery',
 16816: 'sonja',
 63951: 'vani',
 1408: 'woods',
 16115: 'spiders',
 2345: 'hanging',
 2289: 'woody',
 52008: 'trawling',
 52009: "hold's",
 11307: 'comically',
 40830: 'localized',
 30568: 'disobeying',
 52010: "'royale",
 40831: "harpo's",
 52011: 'canet',
 19313: 'aileen',
 52012: 'acurately',
 52013: "diplomat's",
 25242: 'rickman',
 6746: 'arranged',
 52014: 'rumbustious',
 52015: 'familiarness',
 52016: "spider'",
 68804: 'hahahah',
 52017: "wood'",
 40833: 'transvestism',
 34702: "hangin'",
 2338: 'bringing',
 40834: 'seamier',
 34703: 'wooded',
 52018: 'bravora',
 16817: 'grueling',
 1636: 'wooden',
 16818: 'wednesday',
 52019: "'prix",
 34704: 'altagracia',
 52020: 'circuitry',
 11585: 'crotch',
 57766: 'busybody',
 52021: "tart'n'tangy",
 14129: 'burgade',
 52023: 'thrace',
 11038: "tom's",
 52025: 'snuggles',
 29114: 'francesco',
 52027: 'complainers',
 52125: 'templarios',
 40835: '272',
 52028: '273',
 52130: 'zaniacs',

In [53]:
from tensorflow.keras.preprocessing import sequence

max_len = 500
x_train = sequence.pad_sequences(x_train, maxlen=max_len)
x_test = sequence.pad_sequences(x_test, maxlen=max_len)


In [54]:
x_train[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,   

In [55]:
#train rnn model
model = Sequential()
model.add(Embedding(max_features,128,input_length=max_len)) #embedding layers
model.add(SimpleRNN(128,activation="relu"))
model.add(Dense(1,activation='sigmoid'))
model.build(input_shape=(None, max_len))
# model.summary()
model.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

In [56]:
#create an instance of eraly stopping
from tensorflow.keras.callbacks import EarlyStopping
earlystopping = EarlyStopping(monitor='val_loss',patience=5,restore_best_weights=True)
earlystopping

In [57]:
#train the model with earlystopping
history=model.fit(x_train,y_train,epochs=10,batch_size=32,validation_split=0.2,callbacks=[earlystopping])
history

Epoch 1/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 153s 241ms/step - accuracy: 0.6065 - loss: 279.2041 - val_accuracy: 0.6682 - val_loss: 0.5979
Epoch 2/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 203s 242ms/step - accuracy: 0.7181 - loss: 5676.1509 - val_accuracy: 0.6832 - val_loss: 0.5777
Epoch 3/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 200s 239ms/step - accuracy: 0.7862 - loss: 0.4592 - val_accuracy: 0.7928 - val_loss: 0.4493
Epoch 4/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 148s 237ms/step - accuracy: 0.8812 - loss: 0.2869 - val_accuracy: 0.8130 - val_loss: 0.4347
Epoch 5/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 201s 236ms/step - accuracy: 0.9261 - loss: 0.2004 - val_accuracy: 0.8176 - val_loss: 0.4526
Epoch 6/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 147s 235ms/step - accuracy: 0.9485 - loss: 0.1518 - val_accuracy: 0.8106 - val_loss: 0.4898
Epoch 7/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 142s 227ms/step - accuracy: 0.9591 - loss: 0.1234 - val_accuracy: 0.8154 - val_loss: 0.5078
Epoch 8/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 150s 239ms/step - accuracy: 0.9

In [58]:
model.save("simple_rnn_imdb.h5")

In [59]:
# Step 1: Import Libraries and Load the Model
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.models import load_model

In [60]:

# Load the IMDB dataset word index
word_index = imdb.get_word_index()
reverse_word_index = {value: key for key, value in word_index.items()}

In [61]:
# Load the pre-trained model with ReLU activation
model = load_model('simple_rnn_imdb.h5')
model.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_7 (Embedding)              │ (None, 500, 128)            │       1,280,000 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ simple_rnn_5 (SimpleRNN)             │ (None, 128)                 │          32,896 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_5 (Dense)                      │ (None, 1)                   │             129 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 1,313,027 (5.01 MB)

 Trainable params: 1,313,025 (5.01 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 2 (12.00 B)

In [62]:
model.get_weights()

[array([[ 0.02651992,  0.09680493, -0.04780169, ...,  0.04597796,
          0.11355938,  0.15722033],
        [-0.01998845, -0.00907896, -0.03953115, ...,  0.01332356,
          0.01298152,  0.08158801],
        [ 0.01106819,  0.11236243,  0.02213702, ...,  0.06944261,
          0.09367403,  0.05400926],
        ...,
        [-0.01481445,  0.02960089,  0.0315349 , ..., -0.06983229,
         -0.0139469 , -0.04697001],
        [ 0.01619905,  0.0513531 ,  0.01405291, ..., -0.03228583,
         -0.01028186, -0.0230405 ],
        [-0.0735883 ,  0.0150323 ,  0.0497386 , ..., -0.10692184,
         -0.04707113, -0.04675657]], dtype=float32),
 array([[ 0.03456308,  0.09275845, -0.16549568, ..., -0.09243894,
         -0.0718949 ,  0.03967921],
        [-0.01847997, -0.09777694, -0.17423546, ...,  0.0688319 ,
         -0.02448826,  0.15138401],
        [-0.06477266, -0.02995675,  0.04839674, ...,  0.14770283,
         -0.11150562, -0.04588488],
        ...,
        [-0.05409048,  0.17727366, -0.1

In [63]:
# Step 2: Helper Functions
# Function to decode reviews
def decode_review(encoded_review):
    return ' '.join([reverse_word_index.get(i - 3, '?') for i in encoded_review])

# Function to preprocess user input
def preprocess_text(text):
    words = text.lower().split()
    encoded_review = [word_index.get(word, 2) + 3 for word in words]
    padded_review = sequence.pad_sequences([encoded_review], maxlen=500)
    return padded_review

In [64]:
### Prediction  function

def predict_sentiment(review):
    preprocessed_input=preprocess_text(review)

    prediction=model.predict(preprocessed_input)

    sentiment = 'Positive' if prediction[0][0] > 0.5 else 'Negative'

    return sentiment, prediction[0][0]



In [65]:
# Step 4: User Input and Prediction
# Example review for prediction
example_review = "This movie was fantastic! The acting was great and the plot was thrilling."

sentiment,score=predict_sentiment(example_review)

print(f'Review: {example_review}')
print(f'Sentiment: {sentiment}')
print(f'Prediction Score: {score}')

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 257ms/step
Review: This movie was fantastic! The acting was great and the plot was thrilling.
Sentiment: Negative
Prediction Score: 0.001970317680388689
